### ISSUE TITLE
example data

### ISSUE THREAD

**Issue by hfl112** [AbbVie-GRC-Methods-Dev/new_normal#1]
Hi,
Thanks for developing this great methodology for detect tumor-only mutations. Is it possible to upload some maf examples of "data_splits.csv" or the directory structure of  MAF folder, or the final feature table examples for machine learning? 
Cuz, based on the python scripts, it's very obscure to know the exact file format and pipeline to run it. I am using mutect result so I might need to convert the format or column_id to run this pipeline.
Many thanks
Funan

**Comment by kiranchari** [comment]
Hi @hfl112, could you please share an example for how to run this method on a tumor bam file? Thanks!

**Comment by nghuuanbui** [comment]
Hi! 
I have the same issue on how to run your scripts on my samples. May I ask if you can share some test samples (maf files,...) of ''data_splits.csv''? I am also using mutect result so it would be great to know what input is needed to run your scripts and 
how the pipeline works.

Best Regards,
An

**Comment by kiranchari** [comment]
@hfl112 Kindly assist in providing your solution.
